### PR TITLE
Added readme key pair to compose.json

### PR DESCRIPTION
**Pull request by mav2287**
Was looking at this and noticed that the readme key wasn't there.

### CODE REVIEW

**Comment by oscarotero** [comment]
I didn't know this key. What it's for?

**Comment by mav2287** [comment]
I'm not positive where or how it gets used. I am in the habit of having it since sometimes readme is `readme.md` and others `README.md`.  Here is the description on the composer site: [readme](https://getcomposer.org/doc/04-schema.md#readme). I know with other package managers you can ask them for the readme file without actually installing the package, but I'm not sure if composer can do that.

**Comment by oscarotero** [comment]
Ok, no idea about the purpose of this but I've merged anyway. `README.md` is detected automatically by github and packagist, so I guess this is for cases with a different name.

**Comment by mav2287** [comment]
That would be my thought too. I just have always been in the habit of filing it out.

**Pull request merged**
